添加qqwife插件
FloatTech/NanoBot-Plugin pull request #8
Opened 2023-10-22 10:35 UTC by fangliuyu

2023-10-22 11:53 UTC, Jiang-Red requested changes

2023-10-22 11:53 UTC, Jiang-Red commented on plugin/qqwife/happyplay.go
> +	control "github.com/FloatTech/zbputils/control"
别用control，下同

2023-10-22 12:42 UTC, fumiama requested changes

2023-10-22 12:42 UTC, fumiama commented on plugin/qqwife/dbfile.go
> +				_, _ = ctx.SendPlainMessage(false, "[dbfile.go.80 ->ERROR]:", err)
行数无需硬编码，可通过runtime获取。

2023-10-22 12:42 UTC, fumiama commented on plugin/qqwife/dbfile.go
> +		Users:      uid.ID + " & " + target.ID,
新增插件不准备改改这个设计吗？

2023-10-25 16:55 UTC, fangliuyu commented on plugin/qqwife/dbfile.go
> +		Users:      uid.ID + " & " + target.ID,
就这样吧，现在ID都是string，现在只需要切割一下就好比对了（比int64方便就行了x

2023-10-26 14:50 UTC, fumiama commented on plugin/qqwife/dbfile.go
> +		Users:      uid.ID + " & " + target.ID,
好吧

2023-10-26 14:50 UTC, fumiama commented on plugin/qqwife/dbfile.go
> +				_, _ = ctx.SendPlainMessage(false, "[dbfile.go.80 ->ERROR]:", err)
这个注意一下

2023-10-27 14:36 UTC, fumiama approved these changes

2023-10-27 14:36 UTC, merged